### PR TITLE
WP coding standards and minor cosmetics

### PR DESCRIPTION
**Pull request by kingkero**
Hey Leo,

I did some cosmetic changes to your plugin, trying to better adhere to the WordPress Coding Standards as well as PHP best practices

### CODE REVIEW

**Comment by leoek** [comment]
Hey Martin,

why did you remove all the white spaces? I thought the php/wordpress scene wants them 🙈

**Comment by leoek** [comment]
@kingkero You can check them here: https://make.wordpress.org/core/handbook/best-practices/coding-standards/php/#space-usage

**Comment by kingkero** [comment]
@leoek Sorry for that confusion. I tried using [PHP_CodeSniffer with WordPress Coding Standards](https://github.com/WordPress-Coding-Standards/WordPress-Coding-Standards), must have not picked up the correct rules, will rewrite this

**Comment by kingkero** [comment]
@leoek Updated the PR, indeed my `phpcs` had the wrong ruleset. Now there's only two warnings left:
```
╰─➤  phpcs --standard=WordPress index.php                                                                                 1 ↵

FILE: .../wp-mail-env-sensitive/index.php
-----------------------------------------------------------------------------------------
FOUND 0 ERRORS AND 2 WARNINGS AFFECTING 1 LINE
-----------------------------------------------------------------------------------------
 75 | WARNING | error_log() found. Debug code should not normally be used in production.
 75 | WARNING | print_r() found. Debug code should not normally be used in production.
-----------------------------------------------------------------------------------------
```

But having them in this `if` block should be fine

**Pull request merged**
